sudo: false
language: go
go:
  - 1.10.x
  - 1.11.x
  - master

go_import_path: golang.org/x/lint

install:
  - go get -t -v ./...

script:
  - go test -v -race ./...

matrix:
  include:
    - arch: ppc64le
      go: 1.14.x
    - arch: ppc64le
      go: master
  allow_failures:
    - go: master
  fast_finish: true
